name: flutter_template
description: Flutter template app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^10.0.0
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
